Reorder assertion to avoid uninit warning
Fixes the following error:

    write.c: In function ‘chain_frchains_together’:
    write.c:409:24: error: ‘dummy.fr_type’ may be used uninitialized in this
    function [-Werror=maybe-uninitialized]
       gas_assert (prev_frag->fr_type != 0);
                            ^
    write.c:392:9: note: ‘dummy’ was declared here
       fragS dummy, *prev_frag = &dummy;
         ^
Upstream binutils commit 4fc0b46e62cec696390862c9eb7d80b35d24f0f8.

Signed-off-by: Joel Stanley <joel@jms.id.au>