Fixes: "gas/read.c:5087:12: error: left shift of negative"
	PR gas/18446
	* read.c (output_big_sleb128): Use U suffix to prevent compile
	time warning.

(cherry picked from commit 29798047afaa22335a504280a5bbdbafe2b1b63d)
Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>