gas: fix warning seen with GCC 4.9
Using gcc-4.9 on Ubuntu:

    write.c: In function ‘cvt_frag_to_fill’:
    ./config/tc-pore.h:56:76: error: right-hand operand of comma expression has
    no effect [-Werror=unused-value]
     #define md_convert_frag(B, S, F)            (as_fatal (_("convert_frag\n")), 0)
                                                                                ^

The fix is similar to the one in upstream binutils commit
28a0da39c6db871d66b945d3025f69d56e487aa9.

Signed-off-by: Joel Stanley <joel@jms.id.au>